USE E_COMMERCE;
CREATE TABLE category(CAT_ID INT ,CAT_NAME VARCHAR(20) NOT NULL,PRIMARY KEY(CAT_ID));
INSERT INTO category VALUES (1,"BOOKS");
INSERT INTO category VALUES (2,"GAMES");
INSERT INTO category VALUES(3,"GROCERIES");
INSERT INTO category VALUES(4,"ELECTRONICS");
INSERT INTO category VALUES(5,"CLOTHES");
