/*CREATE aA NEW DATABASE OF E_COMMERCE*/
CREATE DATABASE E_COMMERCE;
USE E_COMMERCE;
/*CREATE TABLE supplier*/
CREATE TABLE supplier(SUPP_ID INT PRIMARY KEY,SUPP_NAME varchar(50)NOT NULL
					,SUPP_CITY VARCHAR(50)NOT NULL,SUPP_PHONE VARCHAR(50) NOT NULL);
/*INSERT VALUES IN THE TABLE*/
INSERT INTO supplier VALUES(1, "Rajesh Retails" , "Delhi" ,"1234567890");
INSERT INTO supplier VALUES(2, "Appario Ltd" , "Mumbai" ,"2589631470");
INSERT INTO supplier VALUES(3, "Knome products" , "Banglore" ,"9785462315");
INSERT INTO supplier VALUES(4, "Bansal Retails" , "Kochi" ,"8975463285");
INSERT INTO supplier VALUES(5, "Mittal Ltd" , "Lucknow" ,"7898456532");


